-- AlterTable
ALTER TABLE "FreelancerProfile" ADD COLUMN     "successRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalHours" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalJobs" INTEGER NOT NULL DEFAULT 0;
